name: 镜像 action

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '原镜像名称'
        required: true
        default: 'mysql/mysql-server'
      image_version:
        description: '镜像版本'
        required: true
        default: 'latest'
      target_registry:
        description: '仓库地址'
        required: true
        default: 'registry.cn-hangzhou.aliyuncs.com'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      qywx_robot_url: ${{ secrets.QYWX_ROBOT_URL }}
    steps:
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ github.event.inputs.target_registry }}

      - name: Pull and push Docker image
        run: |
          docker pull ${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_version }}
          docker push ${{ github.event.inputs.target_registry }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_version }}

      - name: qyweixin send message
        if: ${{ env.qywx_robot_url != '' }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.QYWX_ROBOT_URL}}
          IMAGE_URL: ${{ github.event.inputs.target_registry }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_version }}
        with:
          msgtype: markdown
          content: |
            # 镜像同步成功
            ```
            ${{ env.IMAGE_URL }}
            ```
